better

diff --git a/layout/DEBIAN/preinst b/layout/DEBIAN/preinst
--- a/layout/DEBIAN/preinst
+++ b/layout/DEBIAN/preinst
@@ -2,19 +2,21 @@
 
 set -e
 
-if [ -f /usr/bin/debugserver_xcode ]; then
-    rm -rf /usr/bin/debugserver_xcode
+if [ -f /usr/bin/xcodeanydebug ]; then
+    rm -rf /usr/bin/xcodeanydebug
 fi
+
+mkdir -p /usr/bin/xcodeanydebug
 
 if [ -f /rootfs/usr/libexec/debugserver ]; then
     # ios 16.x+
-    cp /rootfs/usr/libexec/debugserver /usr/bin/debugserver_xcode
+    cp /rootfs/usr/libexec/debugserver /usr/bin/xcodeanydebug/debugserver
 
 elif [ -d /rootfs/Developer ] && [ "$(ls -A /rootfs/Developer)" ]; then
     if [ -f /rootfs/Developer/usr/bin/debugserver ]; then
-        cp /rootfs/Developer/usr/bin/debugserver /usr/bin/debugserver_xcode
+        cp /rootfs/Developer/usr/bin/debugserver /usr/bin/xcodeanydebug/debugserver
     else
-        echo "* debugserver for xcode not found on your device" >&2
+        echo -e "\n* debugserver for xcode not found on your device\n\n" >&2
         exit 1
     fi
 else
